[application]

# App (Project) Name
name = "crace"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "业余无线电考试刷题工具"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# fix routing
index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["https://cdn.simplecss.org/simple.min.css", "/custom.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

